site_name: CMT Monitor Documentation
copyright: 2020-2021 - cavaliba.com

theme:
  name: material
  font: false
  language: en

extra_css:
  - stylesheets/extra.css

nav:
  - 'Home': 'index.md'
#  - 'Quickstart': 'quickstart.md'
  - 'Quickstart and Setup': 'setup.md'
  - 'Download': 'download.md'
  - 'Directory structure': 'directory_structure.md'
  - 'Configuration':
      - configuration: configuration.md
      - example: configuration_example.md
#  - 'FAQ': 'faq.md'
  - 'CLI': 'cli.md'
  - 'Cron / Automatic run' : 'cron.md'
  - 'Modules':
      - boottime: check_boottime.md
      - certificate: check_certificate.md
      - cpu: check_cpu.md
      - disk: check_disks.md
      - folder: check_folders.md
      - load: check_load.md
      - memory: check_memory.md
      - mount: check_mounts.md
      - mysql: check_mysql.md
      - mysqldata: check_mysqldata.md
      - ping: check_pings.md
      - process: check_process.md
      - send: check_send.md
      - sendfile: check_sendfile.md
      - socket: check_socket.md
      - swap: check_swap.md
      - url: check_urls.md
  - 'Metrology': 
      - metrology concepts: metrology.md
      - graylog: metrology_graylog.md
      - elastic: metrology_elastic.md
      - influxdb: metrology_influxdb.md
  - 'Alerts, Severity and Pagers':
      - alert concepts : alert_intro.md
      # - Teams
      # - PagerDuty

  - 'Advanced':
      - 'Data model': data_model.md
      - 'Duration item': duration.md
      # 'timerange item' : timerange.md
   #  - 'Dev / How to extend': 'extend.md'
  - 'License': license.md
  - 'Versions': 'version.md'
  - 'Visit cavaliba.com': 'http://www.cavaliba.com'
#- upgrade
#- full configuration
#- ansible

markdown_extensions:
  #- admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      #clickable_checkbox: true
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
